version: "3.9"

services:
  db:
    image: postgres:15
    container_name: weather-db
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
