services:
  db:
    image: postgres:15
    container_name: weather-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
